#  WHILE
#              1) For'un parcalanmis halidir...
#              2) For ile yapabildiginiz herseyi rahatlikla yapabilirsiniz...
#              3) For'dan farki, metotlardan gelen cevaplara gore islem yapabilme yetenegine sahip olmasidir... (ORNEK => ADO.NET konusunda deginecegimiz, "okuyabildigin kadar oku..." metodu gibi... 